stages:
  - build
  - test

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test
